# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vikimaster2/Code/cpp-lsystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vikimaster2/Code/cpp-lsystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vikimaster2/Code/cpp-lsystem/CMakeFiles /Users/vikimaster2/Code/cpp-lsystem//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vikimaster2/Code/cpp-lsystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cuda_lsystem_cpp_debug

# Build rule for target.
cuda_lsystem_cpp_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda_lsystem_cpp_debug
.PHONY : cuda_lsystem_cpp_debug

# fast build rule for target.
cuda_lsystem_cpp_debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/build
.PHONY : cuda_lsystem_cpp_debug/fast

distributions.o: distributions.cpp.o
.PHONY : distributions.o

# target to build an object file
distributions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/distributions.cpp.o
.PHONY : distributions.cpp.o

distributions.i: distributions.cpp.i
.PHONY : distributions.i

# target to preprocess a source file
distributions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/distributions.cpp.i
.PHONY : distributions.cpp.i

distributions.s: distributions.cpp.s
.PHONY : distributions.s

# target to generate assembly for a file
distributions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/distributions.cpp.s
.PHONY : distributions.cpp.s

lsystem.o: lsystem.cpp.o
.PHONY : lsystem.o

# target to build an object file
lsystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/lsystem.cpp.o
.PHONY : lsystem.cpp.o

lsystem.i: lsystem.cpp.i
.PHONY : lsystem.i

# target to preprocess a source file
lsystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/lsystem.cpp.i
.PHONY : lsystem.cpp.i

lsystem.s: lsystem.cpp.s
.PHONY : lsystem.s

# target to generate assembly for a file
lsystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/lsystem.cpp.s
.PHONY : lsystem.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/main.cpp.s
.PHONY : main.cpp.s

types.o: types.cpp.o
.PHONY : types.o

# target to build an object file
types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/types.cpp.o
.PHONY : types.cpp.o

types.i: types.cpp.i
.PHONY : types.i

# target to preprocess a source file
types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/types.cpp.i
.PHONY : types.cpp.i

types.s: types.cpp.s
.PHONY : types.s

# target to generate assembly for a file
types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_lsystem_cpp_debug.dir/build.make CMakeFiles/cuda_lsystem_cpp_debug.dir/types.cpp.s
.PHONY : types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuda_lsystem_cpp_debug"
	@echo "... distributions.o"
	@echo "... distributions.i"
	@echo "... distributions.s"
	@echo "... lsystem.o"
	@echo "... lsystem.i"
	@echo "... lsystem.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... types.o"
	@echo "... types.i"
	@echo "... types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

